<div class="content-wrapper">

  <section class="content-header">
    <h1>Edit Workplan</h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('workplan') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Workplan</li>
    </ol>
  <section>

    <br>

<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


<section class="content">

  <div class="row">
    <div class="col-md-12 col-xs-12">
      
      <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>

          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>-->

                <?php elseif($this->session->flashdata('error')): ?>
                  <div class="alert alert-error alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <?php echo $this->session->flashdata('error'); ?>
                  </div>
        <?php endif; ?>
        <div class="tab-content">

<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        WORKPLAN                                                 -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->  


          <div class="box">
          <form role="form" action="<?php base_url('workplan/update') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">



              <?php echo validation_errors(); ?>

          <div class="row">

                <div class="col-md-3 col-xs-3">
                  <div class="form-group">
                      <label for="major_deliverable">Major Deliverables <font color="red">*</font></label>
                      <input type="text" class="form-control" id="major_deliverable" name="major_deliverable" autocomplete="off"
                      value="<?php echo set_value('major_deliverable',isset($wkplan_data['workplan']['major_deliverable'])? $wkplan_data['workplan']['major_deliverable']:''); ?>">
                  </div>
                </div>

              

                <div class="col-md-3 col-xs-3">
                  <div class="form-group">
                      <label for="duration">Duration<font color="red">*</font></label>
                      <input type="number" class="form-control" id="duration" name="duration" autocomplete="off"
                      value="<?php echo set_value('duration',isset($wkplan_data['workplan']['duration'])? $wkplan_data['workplan']['duration']:''); ?>" />
                  </div>
                </div>


                  <div class="col-md-3 col-xs-3">
                  <div class="form-group">
                    <label for="start_date">Start date <font color="red">*</font></label>
                    <input type="date" class="form-control" id="start_date" name="start_date" autocomplete="off"
                  value="<?php echo set_value('start_date',isset($wkplan_data['workplan']['start_date'])? $wkplan_data['workplan']['start_date']:''); ?>" />
                  </div>
                  </div> 


                  <div class="col-md-3 col-xs-3">
                  <div class="form-group">
                    <label for="end_date">End date <font color="red">*</font></label>
                    <input type="date" class="form-control" id="end_date" name="end_date" autocomplete="off"
                    value="<?php echo set_value('end_date',isset($wkplan_data['workplan']['end_date'])? $wkplan_data['workplan']['end_date']:''); ?>" />
                  </div>
                  </div>  


            </div>


            <div class="row">

              <div class="col-md-3 col-xs-3">
                  <div class="form-group">
               <table class="table table-bordered" id="task_info_table">
                  <thead>
                    <tr>
                      <th style="width:30%">Tasks</th>                     
                      <th style="width:10%"><button type="button" id="add_row" class="btn btn-default"><i class="fa fa-plus"></i></button></th>
                    </tr>
                  </thead>

                   <tbody>
                      <?php if(isset($wkplan_data['task'])): ?>
                      <?php $x = 1; ?>
                      <?php foreach ($wkplan_data['task'] as $key => $val): ?>
                      <tr id="row_<?php echo $x; ?>">
                      <td><input type="text" name="task[]" id="task_<?php echo $x; ?>" class="form-control" required value="<?php echo $val?>" autocomplete="off"></td>

                    <td><button type="button" class="btn btn-default" onclick="removeRow('<?php echo $x; ?>')"><i class="fa fa-close"></i></button></td>
                 </tr>
                 <?php $x++; ?>
               <?php endforeach; ?>
             <?php else: ?>  <!-- We insert a blank line -->

                      

             <?php endif; ?>

                   </tbody>
                </table>
              </div>
            </div>
   
            </div>

            <div class="row">

                 
                    <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="status">Status <font color="red">*</font></label>
                      <input type="text" class="form-control" id="status" name="status" autocomplete="off"
                      value="<?php echo set_value('status',isset($wkplan_data['workplan']['status'])? $wkplan_data['workplan']['status']:''); ?>" />
                    </div>
                    </div>

                    <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="personnel_role">Personnel Roles<font color="red">*</font></label>
                      <input type="text" class="form-control" id="personnel_role" name="personnel_role" autocomplete="off"
                      value="<?php echo set_value('personnel_role',isset($wkplan_data['workplan']['personnel_role'])? $wkplan_data['workplan']['personnel_role']:''); ?>" />
                    </div>
                    </div>


                   <div class="col-md-3 col-xs-3">
                   <div class="form-group">
                      <label for="reschedule_start_date">Rescheduled start date<font color="red">*</font></label>
                      <input type="date" class="form-control" id="reschedule_start_date" name="reschedule_start_date" autocomplete="off"
                      value="<?php echo set_value('reschedule_start_date',isset($wkplan_data['workplan']['reschedule_start_date'])? $wkplan_data['workplan']['reschedule_start_date']:''); ?>" />
                    </div>
                    </div> 

                </div>


                <div class="row">

                       <div class="col-md-3 col-xs-3">
                       <div class="form-group">
                          <label for="reschedule_end_date">Rescheduled end date<font color="red">*</font></label>
                          <input type="date" class="form-control" id="reschedule_end_date" name="reschedule_end_date" autocomplete="off"
                          value="<?php echo set_value('reschedule_end_date',isset($wkplan_data['workplan']['reschedule_end_date'])? $wkplan_data['workplan']['reschedule_end_date']:''); ?>" />
                       </div>
                       </div>   

                       <div class="col-md-3 col-xs-3">
                          <div class="form-group">
                          <label for="consultant_comment">Consultant Comments</label>
                          <textarea type="text" class="form-control" rows="3" id="consultant_comment" name="consultant_comment" autocomplete="off"><?php echo set_value('consultant_comment',isset($wkplan_data['workplan']['consultant_comment'])? $wkplan_data['workplan']['consultant_comment']:''); ?>
                          </textarea>
                         </div>
                       </div>
                    
                        <div class="col-md-3 col-xs-3">
                        <div class="form-group">
                           <label for="consultant_update">Consultant Update</label>
                           <textarea type="text" class="form-control" rows="3" id="consultant_update" name="consultant_update" autocomplete="off"><?php echo set_value('consultant_update',isset($wkplan_data['workplan']['consultant_update'])? $wkplan_data['workplan']['consultant_update']:''); ?></textarea>
                        </div>
                        </div>
                     
                        <div class="col-md-3 col-xs-3">
                        <div class="form-group">
                          <label for="client_comment">Client Comments</label>
                          <textarea type="text" class="form-control" rows="3" id="client_comment" name="client_comment" autocomplete="off"><?php echo set_value('client_comment',isset($wkplan_data['workplan']['client_comment'])? $wkplan_data['workplan']['client_comment']:''); ?></textarea>
                        </div>
                        </div>

                 </div>


                <div class="row">

                      
                      <div class="col-md-3 col-xs-3">
                      <div class="form-group">
                          <label for="client_update">Client Update</label>
                          <textarea type="text" class="form-control" rows="3" id="client_update" name="client_update" autocomplete="off"><?php echo set_value('client_update',isset($wkplan_data['workplan']['client_update'])? $wkplan_data['workplan']['client_update']:''); ?></textarea>
                      </div>
                      </div> 
                     
                      <div class="col-md-3 col-xs-3">
                      <div class="form-group">
                          <label for="monitoring_notes">Monitoring Notes</label>
                          <textarea type="text" class="form-control" rows="3" id="monitoring_notes" name="monitoring_notes" autocomplete="off"><?php echo set_value('monitoring_notes',isset($wkplan_data['workplan']['monitoring_notes'])? $wkplan_data['workplan']['monitoring_notes']:''); ?></textarea>
                      </div>
                      </div>

                      <div class="col-md-4 col-xs-4">
                      <div class="form-group">
                        <label for="monitoring_dates">Monitoring  Dates<font color="red">*</font></label>
                        <input type="date" class="form-control" id="monitoring_dates" name="monitoring_dates" autocomplete="off"
                        value="<?php echo set_value('monitoring_dates',isset($wkplan_data['workplan']['monitoring_dates'])? $wkplan_data['workplan']['monitoring_dates']:''); ?>"/>
                      </div>
                      </div>   

                 </div>           
                 

             <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="<?php echo base_url('workplan/') ?>" class="btn btn-warning">Close</a>
              </div>
            </div>
          </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</section>
</section>
</div>

        




 

            




<!-----------------------------------------   Javascript  --------------------------------------->

<script type="text/javascript">




// Add new row in the table 
       $("#add_row").unbind('click').bind('click', function() 
    {
      var table = $("#task_info_table");
      var count_table_tbody_tr = $("#task_info_table tbody tr").length;
      var row_id = count_table_tbody_tr + 1;

      $.ajax({
          success:function(response) {            

               var html = '<tr id="row_'+row_id+'">'+
  
                   '<td><input type="text" name="task[]" id="task_'+row_id+'" class="form-control" </td>'+
                
                    '<td><button type="button" class="btn btn-default" onclick="removeRow(\''+row_id+'\')"><i class="fa fa-close"></i></button></td>'+
                    '</tr>';

                if(count_table_tbody_tr >= 1) {$("#task_info_table tbody tr:last").after(html);}
                else {$("#task_info_table tbody").html(html);}

                $(".option").select2();
          }
        });

      return false;

    });


   
   function removeRow(tr_id)
    {

    $("#task_info_table tbody tr#row_"+tr_id).remove();

    }


</script>